FROM node:18

WORKDIR /app/unulearner-frontend

ENV PATH /app/unulearner-frontend/node_modules/.bin:$PATH

COPY package*.json /app/unulearner-frontend/

RUN npm install
RUN npm install -g @angular/cli@latest

COPY . /app/unulearner-frontend

CMD ["ng", "serve", "--host", "0.0.0.0", "--port", "9999", "--disable-host-check", "--proxy-config", "proxy.conf.json"]
